tg:
  token: 6998842098:AAGnia5pUjyTqcwPnYjR1K8_HBeZ0ZgoGMA
  channel: tipitest

vk:
  token: vk1.a.ZR_7Xn-ovN96V-Cj_HFl0wQDDdCkkwLclRMwqj-dyAvQuNOGBDUXSfhjTx1izt1-dqZD-BzkpC0q_XZLSPq7REyIi68HRO0I6U3YIPpR-4_Afo9srp0oJ4pUd-5RkhdZpHdhiD1KJWwUpOthVZDZ-YqQjP5x0V1CADCvggtidHPZ8FDHr7g0C11GY4yD4QdCktFC8n32hqdi9saCzuPK-Q
  long: 227332040